apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: k8s-demo-app
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 5000
