namespace: dev
environment: dev
version: "1.1.0"
replicas: 2

image:
  repository: k8s-demo-app
  tag: "1.1.0"
  pullPolicy: Never

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

featureFlags:
  newUI: "true"
